import { useState } from "react";
import { Link } from "react-router-dom";
import { FileSpreadsheet, FileText } from "lucide-react";
import { AppShell } from "../components/layout/AppShell";
import { Card, CardHeader } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Badge } from "../components/ui/Badge";
import { InfoNotice, ServiceErrorNotice } from "../components/ui/Notices";
import { EmptyState, LoadingState } from "../components/ui/States";
import { Table } from "../components/ui/Table";
import { useApi } from "../lib/useApi";
import { api, downloadReport, errorMessage } from "../services/api";

interface RunRow {
  id: string;
  kind: string;
  created_at: string;
}

const KINDS = [
  { key: "optimization", label: "Optimisation run" },
  { key: "scenario", label: "Scenario run" },
  { key: "prediction", label: "Fuel prediction" },
];

/** Where each run kind can be reopened in full, by id. */
const VIEW_PATH: Record<string, string> = {
  optimization: "/results",
  scenario: "/scenarios",
  prediction: "/prediction",
};

export default function Reports() {
  const history = useApi(() => api.reportHistory(), []);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");

  const pdfAvailable = history.data?.pdf_available ?? false;

  async function download(format: "csv" | "pdf", kind: string, runId?: string) {
    setError("");
    setBusy(`${format}:${runId ?? kind}`);
    try {
      await downloadReport(format, kind, runId);
    } catch (err) {
      setError(errorMessage(err));
    } finally {
      setBusy("");
    }
  }

  return (
    <AppShell title="Reports & Export" subtitle="Download the runs stored against your account.">
      <InfoNotice message="Exports are generated by the API from the stored run. Each file carries a provenance header listing the run id and the conversion factors used for cost and emissions." />
      {!pdfAvailable && history.data && (
        <ServiceErrorNotice
          title="PDF export unavailable"
          message="The backend reports that ReportLab is not installed, so only CSV export is available. Install it with `pip install reportlab` and restart the API."
        />
      )}
      {error && <ServiceErrorNotice title="Export failed" message={error} />}
      {history.error && <ServiceErrorNotice message={history.error} />}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {KINDS.map((kind) => (
          <Card key={kind.key} hover>
            <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700">
              <FileSpreadsheet size={19} />
            </span>
            <p className="mt-3 text-sm font-bold text-navy-900">{kind.label}</p>
            <p className="mt-1 text-xs text-slate-500">Exports your most recent {kind.label.toLowerCase()}.</p>
            <div className="mt-4 flex flex-wrap gap-2">
              <Button size="sm" variant="outline" disabled={!!busy} onClick={() => download("csv", kind.key)}>
                CSV
              </Button>
              <Button
                size="sm"
                variant="ghost"
                disabled={!!busy || !pdfAvailable}
                onClick={() => download("pdf", kind.key)}
              >
                PDF
              </Button>
            </div>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader title="Recent runs" subtitle="Stored by the API against your account." />
        {history.loading && <LoadingState label="Loading history…" />}
        {!history.loading && (history.data?.items.length ?? 0) === 0 && (
          <EmptyState
            title="Nothing to export yet"
            description="Run a prediction, an optimisation or a scenario analysis and it will appear here."
          />
        )}
        {!history.loading && (history.data?.items.length ?? 0) > 0 && (
          <Table<RunRow>
            keyField={(r) => r.id}
            data={history.data!.items}
            columns={[
              { header: "Run", accessor: (r) => <span className="font-semibold">{r.id}</span> },
              {
                header: "Type",
                accessor: (r) => <Badge tone={r.kind === "optimization" ? "teal" : "navy"}>{r.kind}</Badge>,
              },
              {
                header: "Created",
                accessor: (r) => new Date(r.created_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }),
                align: "right",
              },
              {
                header: "",
                accessor: (r) => (
                  <div className="flex justify-end gap-1">
                    <Link to={`${VIEW_PATH[r.kind] ?? "/reports"}?run=${r.id}`}>
                      <Button size="sm" variant="outline">
                        View
                      </Button>
                    </Link>
                    <Button size="sm" variant="ghost" disabled={!!busy} onClick={() => download("csv", r.kind, r.id)}>
                      CSV
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      disabled={!!busy || !pdfAvailable}
                      onClick={() => download("pdf", r.kind, r.id)}
                    >
                      <FileText size={13} />
                    </Button>
                  </div>
                ),
                align: "right",
              },
            ]}
          />
        )}
      </Card>
    </AppShell>
  );
}
